# Site settings
baseurl = "https://ozunconf17.ropensci.org"
canonifyurls = true
relativeurls = false
languageCode = "en-us"
title = "rOpenSci OzUnconference"
location = "Melbourne 2017"
theme = "hugo-ropensci-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "rOpenSci OzUnconference"
  description = "Melbourne, Australia. 26-27 October 2017"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Sorry, but you seem to have become lost."
    text = "Please visit [the front page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "rOpenSci"
    # Optional logo as brand stored in img/
    logo = "ropensci_small.png"
    about = "What"
    team = "Who"
    joinus="Join Us"
    venue = "Venue"
    sponsors = "Sponsors"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "rOpenSci OzUnconf"
    subtitle = "26-27 October 2017 • Melbourne • Australia"
    buttonText = "Tell me more"


   # About section
   [params.about]
    enable = true
    title = "The OzUnconference"
    text = "For a second year running, we are excited to announce another [rOpenSci](http://ropensci.org/) OzUnconference in 2017 held in Melbourne, Australia. We're organizing this event to bring together scientists, developers, and open data enthusiasts from academia, industry, government, and non-profit to get together for a few days and hack on various projects. Past projects have related to open data, data visualization, data publication and open science using R. To ensure a safe, enjoyable, and friendly experience for everyone who participates, we have a strict [code of conduct](/coc) and [terms and conditions](/terms).\n\n All OzUnconference ideas will begin as GitHub issues on the [OzUnconf repo](https://github.com/ropensci/ozunconf17/issues/) in the weeks before the event. However, the actual schedule will not be decided until the morning of the 26th. You can see some of the [projects proposed](https://github.com/ropensci/auunconf/issues) for last year's event in Australia, and the [projects proposed](https://github.com/ropensci/unconf17/issues) at the unconf in LA earlier this year."

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    text = "We are assembling an exciting team of developers and enthusiastic users representing academia, industry, government, and various open source projects."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]]
      name = "Nicholas Tierney"
      position = "Monash University"
      img = "nicholas-tierney.jpg"
      twitter = "nj_tierney"
      github = "njtierney"
      url = "http://www.njtierney.com/"

    [[params.team.members]]
      name = "Di Cook"
      position = "Monash University"
      img = "di-cook.jpg"
      twitter = "visnut"
      github = "dicook"
      url = "http://dicook.org"

    [[params.team.members]]
      name = "Rob Hyndman"
      position = "Monash University"
      img = "rob-hyndman.png"
      twitter = "robjhyndman"
      github = "robjhyndman"
      url = "https://robjhyndman.com"

    [[params.team.members]]
      name = "Miles McBain"
      position = "Queensland University of Technology"
      img = "miles-mcbain.jpg"
      twitter = "milesmcbain"
      github = "MilesMcBain"
      url = "https://acems.org.au/our-people/miles-mcbain"

    [[params.team.members]]
      name = "Roger Peng"
      position = "Johns Hopkins University"
      img = "roger-peng.png"
      twitter = "rdpeng"
      github = "rdpeng"
      url = "http://www.biostat.jhsph.edu/~rpeng/"

    [[params.team.members]]
      name = "Jessie Roberts"
      position = "Queensland University of Technology"
      img = "jessie-roberts.jpg"
      twitter = "_jessie_roberts"
      github = "jesse-jesse"
      url = "https://acems.org.au/our-people/jessie-roberts"

    [[params.team.members]]
      name = "Earo Wang"
      position = "Monash University"
      img = "earo-wang.jpg"
      twitter = "earowang"
      github = "earowang"
      url = "http://earo.me"

    [[params.team.members]]
      name = "Charles Gray"
      position = "La Trobe University"
      img = "charles-gray.jpg"
      twitter = "cantabile"
      url = "http://choosemaths.org.au/charles-gray/"
    
    [[params.team.members]]
      name = "Stefan Milton Bache"
      position = "Redbubble"
      img = "stefan-milton-bache.jpg"
      twitter = "https://twitter.com/stefanbache"
      github = "https://github.com/smbache"
      url = "http://stefanbache.dk/"
      
      [[params.team.members]]
      name = "Steph de Silva"
      position = "Rex Analytics"
      img = "steph-de-silva.png"
      twitter = "StephdeSilva"
      github = "stephdesilva"
      url = "www.rex-analytics.com"
    
    [[params.team.members]]
      name = "Peter Ellis"
      position = "Stats NZ"
      img = "peter-ellis.jpg"
      twitter = "ellis2013nz"
      github = "ellisp"
      url = "https://ellisp.github.io"
    
    [[params.team.members]]
      name = "Nick Golding"
      position = "University of Melbourne"
      img = "nick-golding.jpg"
      twitter = "_NickGolding_"
      github = "https://github.com/goldingn"
      url = ""
      
    [[params.team.members]]
      name = "Holly Kirk"
      position = "University of Melbourne"
      img = "holly-kirk.jpg"
      twitter = "HollyKirk"
      github = "hollylkirk"
      url = ""
      
    [[params.team.members]]
      name = "Elle Saber"
      position = "Australian National University"
      img = "elle-saber.jpg"
      twitter = "@ellesaber"
      github = "ellesaber"
      url = ""
    
    [[params.team.members]]
      name = "Michael Sumner"
      position = "Australian Antarctic Division and Antarctic & Climate Ecosystems CRC"
      img = "michael-sumner.png"
      twitter = "mdsumner"
      github = "mdsumner"
      url = "http://www.antarctica.gov.au/"
    
    
    [[params.team.members]]
      name = "Kate Saunders"
      position = "University of Melbourne"
      img = "kate-saunders.png"
      twitter = "KateRobSau"
      github = "saundersk1"
      url = ""
    
    [[params.team.members]]
      name = "Peter Hickey"
      position = "Johns Hopkins University"
      img = "peter-hickey.jpg"
      twitter = "PeteHaitch"
      github = "PeteHaitch"
      url = "peter-hickey"
      
      
    [[params.team.members]]
      name = "Anikó Tóth"
      position = "Macquarie University"
      img = "aniko-toth.jpg"
      twitter = ""
      github = "anikobtoth"
      url = ""
    
    [[params.team.members]]
      name = "Richard Beare"
      position = "Monash University"
      img = "richard-beare.jpg"
      twitter = ""
      github = "richardbeare"
      url = ""
      
    [[params.team.members]]
      name = "Liz Martin"
      position = "University of Melbourne"
      img = "liz-martin.jpg"
      twitter = "lizhmartin"
      github = "lizhmartin"
      url = ""
      
     [[params.team.members]]
      name = "Jeff Hanson"
      position = "University of Queensland"
      img = "jeff-hanson.jpg"
      twitter = "jeff_o_hanson"
      github = "jeffreyhanson"
      url = "http://jeffrey-hanson.com/"
      
    [[params.team.members]]
      name = "Jono Carroll"
      position = "Genentech"
      img = "jono-carroll.jpg"
      twitter = "carroll_jono"
      github = "jonocarroll"
      url = "https://jcarroll.com.au/"
      
    [[params.team.members]]
      name = "Samithree Rajapaksha"
      position = "Monash University"
      img = "samithree-rajapaksha.jpg"
      twitter = ""
      github = ""
      url = ""
      
    [[params.team.members]]
      name = "Saras Mei Windecker"
      position = "University of Melbourne"
      img = "saras-mei-windecker.jpg"
      twitter = "smwindecker"
      github = "smwindecker"
      url = ""
      
    
    [[params.team.members]]
      name = "Damjan Vukcevic"
      position = "University of Melbourne, MCRI"
      img = "damjan-vukcevic.jpg"
      twitter = "vukcevicd"
      github = "dvukcevic"
      url = "http://damjan.vukcevic.net/"
    
    
    [[params.team.members]]
      name = "Grahame Grieve"
      position = "Hl7 FHIR"
      img = "grahame-grieve.jpg"
      twitter = "grahamegrieve"
      github = "grahamegrieve"
      url = "http://www.healthintersections.com.au"
    
    
    [[params.team.members]]
      name = "Daniel Falster"
      position = "University of New South Wales"
      img = "daniel-falster.jpg"
      twitter = "adaptive_plant"
      github = "dfalster"
      url = "http://danielfalster.com/"
      
    [[params.team.members]]
      name = "Nikeisha Caruana"
      position = "La Trobe University"
      img = "nikeisha-caruana.jpg"
      twitter = "bluebirdi"
      github = "njcaruana"
      url = ""
      
    [[params.team.members]]
      name = "Mathew Ling"
      position = "Deakin University"
      img = "mathew-ling.jpg"
      twitter = "lingtax"
      github = "Lingtax"
      url = "http://mathewling.online/about"
    
    [[params.team.members]]
      name = "Hugh Parsonage"
      position = "Grattan Institute"
      img = "hugh-parsonage.jpg"
      twitter = "hughparsonage"
      github = "hughparsonage"
      url = "http://www.github.com/hughparsonage"
      
    [[params.team.members]]
      name = "Madeline Davey"
      position = "University of Queensland"
      img = "madeline-davey.jpg"
      twitter = "Madeline_Davey"
      github = ""
      url = "https://www.coralcoe.org.au/person/madeline-davey"
    
    [[params.team.members]]
      name = "Tim Hyndman"
      position = "University of Melbourne"
      img = "tim-hyndman.png"
      twitter = "timothyhyndman"
      github = "TimothyHyndman"
      url = ""
      
    [[params.team.members]]
      name = "Anna Quaglieri"
      position = "WEHi"
      img = "anna-quaglieri.jpg"
      twitter = "annaquagli"
      github = "annaquaglieri16"
      url = ""
      
    [[params.team.members]]
      name = "Diego Barneche"
      position = "Monash University"
      img = "diego-barneche.jpg"
      twitter = "dbarneche"
      github = "dbarneche"
      url = "https://scholar.google.com.au/citations?user=V1-2VSUAAAAJ&hl=en"
    
    [[params.team.members]]
      name = "Ross Gayler"
      position = "Independent Consultant & Researcher"
      img = "ross-gayler.jpg"
      twitter = "ross_gayler"
      github = "rgayler"
      url = "https://www.researchgate.net/profile/Ross_Gayler"
      
    [[params.team.members]]
      name = "Jackson Kwok"
      position = "University of Melbourne"
      img = "jackson-kwok.jpg"
      twitter = ""
      github = "https://github.com/kcf-jackson"
      url = "https://github.com/kcf-jackson"
      
    [[params.team.members]]
      name = "Natasha Cadenhead"
      position = "University of Melbourne"
      img = "natasha-cadenhead.jpg"
      twitter = "tashcadenhead"
      github = "tashcaden"
      url = ""
      
    [[params.team.members]]
      name = "Adam Gruer"
      position = "Royal Children's Hospital"
      img = "adam-gruer.jpg"
      twitter = "AdamGruer"
      github = "adam-gruer"
      url = ""
      
    [[params.team.members]]
      name = "Yan Holtz"
      position = "University of Queensland"
      img = "yan-holtz.jpg"
      twitter = ""
      github = "https://github.com/holtzy/"
      url = "https://www.linkedin.com/in/yan-holtz-2477534a/?ppe=1"
    
    [[params.team.members]]
      name = "Steve Bennett"
      position = "opencouncildata.org"
      img = "steve-bennett.jpg"
      twitter = ""
      github = "https://github.com/steveage"
      url = "https://stevebennett.me/"
    

# Join us section
  [params.joinus]
  enable=true
  title = "Join us (nominations have closed)"
  text = "The rOpenSci OzUnconference is our annual event loosely modeled on Foo Camp. This event is unlike many other unconferences in that it is mostly invite-only (past attendees often recommend new ones) with a few spots set aside for self-nominations from the community at large. The agenda is mostly decided during the conference itself. \n\n  Nominations are closed for this year's event but stay tuned for the 2018 announcement early next year."

# Venue section
  [params.venue]
  enable=true
  title = "Venue"
  text = "The event will be hosted at the [Monash University City Campus](https://www.monash.edu/international-business/city-location), 271 Collins St, Melbourne."
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2506.0017421908883!2d144.96399009831677!3d-37.81666758179523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b445ced581%3A0x49e1540573e765e0!2s271+Collins+St%2C+Melbourne+VIC+3004!5e0!3m2!1sen!2sau!4v1504484084976"

  # Sponsors section

    [params.sponsors_list]
      enable = true
      # Possibility to center items
      #center = true
      title = "Sponsors"
      text = "We are extremely grateful to all the sponsors for this year's event. If your organization would like to sponsor the OzUnconf, please email nicholas.tierney [at] monash edu for a sponsorship prospectus."

      # All the clients' logos are stored under 'static/img/sponsors'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors]]
        logo = "ropensci-lettering-colour.png"
        link = "http://ropensci.org"

      [[params.sponsors]]
        logo = "rstudio-logo.png"
        link = "http://rstudio.com"


  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    text  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "nicholas.tierney@monash.edu"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."
    text = "[Contact us](https://njtierney.typeform.com/to/RYOPYW) for more information about the event. This page is available at [this repo](https://github.com/ropensci/ozunconf17). Corrections, changes, and suggestions for improvement are welcome as pull requests."

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
